CREATE TABLE IF NOT EXISTS "TMR" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text,
	"dob" text,
	"email" text,
	"phone" text,
	"facebook" text,
	"gender" text,
	"uni" text,
	"otheruni" text,
	"livingplace" text,
	"highschool" text,
	"uniplace" text,
	"universityyear" text,
	"major" text,
	"long1" text,
	"long2" text,
	"long3" text,
	"long4" text,
	"long5" text,
	"long6" text,
	"long7" text,
	"long8" text,
	"channel" text,
	"sonder" text,
	"gocamp" text,
	"receiveinformation" text,
	"timeperweek" text,
	"appliedbefore" text,
	"mostpreferred" text,
	"secondpreferred" text
);
